refactor and add safety checks

diff --git a/pbuilder-amd64-helper b/pbuilder-amd64-helper
--- a/pbuilder-amd64-helper
+++ b/pbuilder-amd64-helper
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -eo pipefail
+
 if [ -e /etc/debian_chroot ]; then
 	>&2 echo -e "\e[91mERROR (!) Should not be run in a chroot environment\e[0m"
 	exit 1
@@ -19,13 +21,13 @@ Ensure the deb package meets Debian Policy standards.
 
   Options:
   --mirror [suite]                         create a chroot from the Debian mirror
-  --iso [suite] [path-to-iso]              create a chroot from an ISO file
-  --login [path-to-tgz]                    login to tgz
-  --login-save [path-to-tgz]               login to tgz with save mode
-  --build [path-to-tgz]                    build package without tests
-  --build [path-to-tgz] with-tests         build package with tests
-  --build-debug [path-to-tgz]              build package with debug symbols
-  --build-with-checks [path-to-tgz]        build package with Debian checks
+  --iso [suite] [/path/to/iso]             create a chroot from an ISO file
+  --login [/path/to/tgz]                   login to tgz
+  --login-save [/path/to/tgz]              login to tgz with save mode
+  --build [/path/to/tgz]                   build package without tests
+  --build [/path/to/tgz] with-tests        build package with tests
+  --build-debug [/path/to/tgz]             build package with debug symbols
+  --build-with-checks [/path/to/tgz]       build package with Debian checks
   --help                                   display usage information and exit
 
 EOF
@@ -170,7 +172,7 @@ create_chroot()
 	[ -z $iso_name ] && target="/$suite-chroot${iso_name/.iso}" || \
 	target="/$suite-chroot-${iso_name/.iso}"
 
-	if mount | grep $target &>/dev/null; then
+	if mountpoint -q $target; then
 		>&2 echo -e "\e[91mERROR (!) chroot '$target' already to use\e[0m"
 		exit 1
 	fi
@@ -281,6 +283,10 @@ case $1 in
 
 	"--iso")
 		[ $# != 3 ] && usage 1
+		if [ ! -f $3 ]; then
+			>&2 echo -e "\e[91mERROR (!) ISO file '$3' not found\e[0m"
+			exit 1
+		fi
 		init_chroot $1 $2 $3
 	;;
 
